### PR TITLE
fix: fix handling of text fields sensitivity

### PR DESCRIPTION
**Pull request by krystofcelba**

### CODE REVIEW

**Review by vaclav-halik-smartlook — CHANGES_REQUESTED** [review]
Maybe I don't understand it, but I looked at the surrounding code. It doesn't seem right. The first condition doesn't make sense to me. 

Example:
You have a view on a page and in it 2x `UITextField`. You try to set the second one in the sequence as blacklisted. But your current code will mark the first one on the page.

**Comment by krystofcelba** [comment]
@vaclav-halik-smartlook It works a bit differently. The code for traversing the view nodes is called for example in function [setViewIsSensitive:(nonnull NSNumber*)reactTag isSensitive:(BOOL)isSensitive](https://github.com/smartlook/smartlook-react-native-bridge/blob/bf8b2373828855848e2c054fa3a7a16f4868b156/ios/RNSmartlook.m#L378) which is called with the reference to concrete view which sensitivity should be changed. The reason for the traversing is that in the latest RN versions we don't get reference directly to UITextField but to some wrapper and the UITextField we need is a subview of it.

**Comment by vaclav-halik-smartlook** [comment]
Explained, that's correct.

**Review by vaclav-halik-smartlook — APPROVED** [review]
OK

**Pull request merged**
